import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import streamlit as st
import uuid
import time
from datetime import datetime, date, timedelta
from memory.ltm_manager import summarize_and_save, load_memories
from memory.ltm import init_ltm, delete_memories, list_memories
from fpdf import FPDF
import requests as req
from llms.config import settings





st.set_page_config(
    page_title="ProjectSmith AI",
    page_icon="🔨",
    layout="centered"
)

API = st.secrets.get("FAST_API", os.getenv("FAST_API", "https://projectsmith-ai.onrender.com"))

init_ltm()

PLAN_TRIGGERS = {
    "plan it", "plan this", "build it",
    "let's plan", "lets plan", "go", "start planning"
}


def escape_dollars(text: str) -> str:
    """Prevent Streamlit from interpreting $ as LaTeX delimiters."""
    return text.replace("$", r"\$")


# ─── Build full conversation context for planning nodes ────────────────────────
def build_context(messages: list) -> str:
    lines = []
    for msg in messages:
        role = "User" if msg["role"] == "user" else "ProjectSmith"
        lines.append(f"{role}: {msg['content']}")
    return "\n".join(lines)


# ─── Sidebar CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
.session-group-label {
    font-size: 0.72rem;
    font-weight: 600;
    color: #8e8ea0;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 10px 4px 4px 4px;
}
div[data-testid="stSidebar"] button[kind="secondary"] {
    background:    transparent !important;
    border:        none        !important;
    box-shadow:    none        !important;
    text-align:    left        !important;
    padding:       4px 6px     !important;
    font-size:     0.83rem     !important;
    color:         #d1d5db     !important;
    border-radius: 6px         !important;
    width:         100%        !important;
}
div[data-testid="stSidebar"] button[kind="secondary"]:hover {
    background: rgba(255,255,255,0.08) !important;
    color: #ffffff !important;
}
</style>
""", unsafe_allow_html=True)


# ─── PDF generator ─────────────────────────────────────────────────────────────
def generate_pdf(plan, cost, edges, prd, idea):
    def clean(text):
        return (
            text
            .replace("—", "-").replace("–", "-")
            .replace("\u201c", '"').replace("\u201d", '"')
            .replace("\u2018", "'").replace("\u2019", "'")
            .replace("\u2026", "...").replace("\u2022", "-")
            .replace("\u2605", "*").replace("\u2705", "")
            .replace("\u26a0\ufe0f", "!").replace("\U0001f4cb", "")
            .replace("\U0001f4b0", "").replace("\U0001f4c4", "")
            .encode("latin-1", "replace").decode("latin-1")
        )

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "ProjectSmith AI", ln=True, align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Project: {clean(idea[:60])}", ln=True, align="C")
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Generated by AI - validate with real experts before acting.", ln=True, align="C")
    pdf.ln(8)

    for title, content in [
        ("Project Plan",       plan),
        ("Cost & Stack",       cost),
        ("Edge Cases & Risks", edges),
        ("Project Brief",      prd),
    ]:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_fill_color(230, 230, 230)
        pdf.cell(0, 9, title, ln=True, fill=True)
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, clean(content))
        pdf.ln(6)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 5,
        "Disclaimer: This document was generated by ProjectSmith AI. "
        "It is intended for ideation purposes only. Please consult a qualified "
        "business advisor, lawyer, or accountant before making financial or legal decisions."
    )
    return bytes(pdf.output())


# ─── Date grouping helper ──────────────────────────────────────────────────────
def group_by_date(mems):
    today     = date.today()
    yesterday = today - timedelta(days=1)
    week_ago  = today - timedelta(days=7)
    groups    = {"Today": [], "Yesterday": [], "Previous 7 Days": [], "Older": []}

    for m in mems:
        raw = m.get("created_at", "")
        try:
            created = datetime.fromisoformat(raw.replace("Z", "+00:00")).date()
        except Exception:
            created = None

        if created == today:
            groups["Today"].append(m)
        elif created == yesterday:
            groups["Yesterday"].append(m)
        elif created and created >= week_ago:
            groups["Previous 7 Days"].append(m)
        else:
            groups["Older"].append(m)

    return [(label, items) for label, items in groups.items() if items]


def session_title(m):
    content    = m.get("content", "").strip()
    first_line = content.split("\n")[0].strip()
    return first_line[:32] + ("..." if len(first_line) > 32 else "")


# ─── Session state init ────────────────────────────────────────────────────────
for key, default in {
    "user_id":          None,
    "thread_id":        str(uuid.uuid4()),
    "messages":         [],
    "session_messages": [],
    "ltm_context":      "",
    "plan_result":      None,
    "confirm_delete":   False,
    "preview_mem":      None,
}.items():
    if key not in st.session_state:
        st.session_state[key] = default


# ─── Login screen ──────────────────────────────────────────────────────────────
if not st.session_state.user_id:
    st.title("🔨 ProjectSmith AI")
    st.subheader("Your AI startup advisor")
    st.write("Tell me your project idea and I'll help you plan it, price it, and avoid the pitfalls.")
    st.divider()
    st.caption(
        "⚠️ Do not share sensitive business information. "
        "ProjectSmith is an AI tool for ideation only — not a substitute "
        "for professional legal or financial advice."
    )
    st.divider()
    user_id = st.text_input("Enter your name to get started:", placeholder="e.g. austin")
    if st.button("Start", use_container_width=True) and user_id.strip():
        st.session_state.user_id     = user_id.strip()
        st.session_state.ltm_context = load_memories(user_id.strip(), "advisor")
        st.rerun()
    st.stop()


# ─── Main app ──────────────────────────────────────────────────────────────────
st.title("🔨 ProjectSmith AI")

with st.sidebar:

    st.write(f"👤 **{st.session_state.user_id}**")
    st.write(f"🧵 `{st.session_state.thread_id[:8]}...`")
    st.divider()

    if st.button("🆕 New Project", use_container_width=True):
        if st.session_state.session_messages:
            summarize_and_save(
                st.session_state.session_messages,
                st.session_state.user_id,
                "advisor"
            )
        st.session_state.thread_id        = str(uuid.uuid4())
        st.session_state.messages         = []
        st.session_state.session_messages = []
        st.session_state.plan_result      = None
        st.session_state.confirm_delete   = False
        st.session_state.preview_mem      = None
        st.session_state.ltm_context      = load_memories(st.session_state.user_id, "advisor")
        st.rerun()

    if st.button("🚪 Log Out", use_container_width=True):
        if st.session_state.session_messages:
            summarize_and_save(
                st.session_state.session_messages,
                st.session_state.user_id,
                "advisor"
            )
        for key in list(st.session_state.keys()):
            del st.session_state[key]
        st.rerun()

    st.divider()
    st.caption("Type your idea. When ready, type **'plan it'** to generate your full plan.")
    st.divider()
    st.caption("⚠️ Always validate AI advice with real experts.")

    mems = list_memories(st.session_state.user_id) if st.session_state.user_id else []

    if not mems:
        st.markdown(
            "<div style='color:#8e8ea0;font-size:0.8rem;padding:8px 4px;'>"
            "No past sessions yet.</div>",
            unsafe_allow_html=True
        )
    else:
        sorted_mems = sorted(mems, key=lambda m: m.get("created_at", ""), reverse=True)
        grouped     = group_by_date(sorted_mems)

        for group_label, group_mems in grouped:
            st.markdown(
                f"<div class='session-group-label'>{group_label}</div>",
                unsafe_allow_html=True
            )

            for m in group_mems:
                mem_id = m.get("id", "")
                title  = session_title(m)
                col_title, col_del = st.columns([6, 1])

                with col_title:
                    if st.button(title, key=f"view_{mem_id}", use_container_width=True):
                        st.session_state.preview_mem = (
                            None if st.session_state.preview_mem == mem_id else mem_id
                        )
                        st.rerun()

                with col_del:
                    if st.button("🗑️", key=f"del_{mem_id}"):
                        delete_memories(mem_id)
                        if st.session_state.preview_mem == mem_id:
                            st.session_state.preview_mem = None
                        st.toast("Session deleted.", icon="🗑️")
                        st.rerun()

                if st.session_state.preview_mem == mem_id:
                    with st.container(border=True):
                        st.caption(m.get("content", "No content available."))

        st.divider()
        if not st.session_state.confirm_delete:
            if st.button("🧹 Clear All", use_container_width=True):
                st.session_state.confirm_delete = True
                st.rerun()
        else:
            st.warning("Delete **all** sessions?")
            col_yes, col_no = st.columns(2)
            with col_yes:
                if st.button("✅ Yes", use_container_width=True):
                    for m in mems:
                        if m.get("id"):
                            delete_memories(m["id"])
                    st.session_state.confirm_delete = False
                    st.session_state.preview_mem    = None
                    st.toast("All sessions cleared.", icon="🧹")
                    st.rerun()
            with col_no:
                if st.button("❌ No", use_container_width=True):
                    st.session_state.confirm_delete = False
                    st.rerun()


# ─── Chat history ──────────────────────────────────────────────────────────────
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])


# ─── Plan result display ───────────────────────────────────────────────────────
if st.session_state.plan_result:
    result = st.session_state.plan_result
    st.divider()
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("📋 Plan")
        st.markdown(escape_dollars(result.get("plan", "")))        # ← fixed
        st.subheader("⚠️ Edge Cases")
        st.markdown(escape_dollars(result.get("edges", "")))       # ← fixed
    with col2:
        st.subheader("💰 Cost & Stack")
        st.markdown(escape_dollars(result.get("cost", "")))        # ← fixed
        st.subheader("📄 Project Brief")
        st.markdown(escape_dollars(result.get("prd", "")))         # ← fixed
    st.divider()

    idea      = st.session_state.messages[0]["content"] if st.session_state.messages else "project"
    pdf_bytes = generate_pdf(
        result.get("plan", ""), result.get("cost", ""),
        result.get("edges", ""), result.get("prd", ""), idea
    )

    col_a, col_b = st.columns(2)
    with col_a:
        st.download_button(
            label="📥 Download PDF", data=pdf_bytes,
            file_name="project_brief.pdf", mime="application/pdf",
            use_container_width=True
        )
    with col_b:
        st.download_button(
            label="📝 Download Markdown", data=result.get("prd", ""),
            file_name="project_brief.md", mime="text/markdown",
            use_container_width=True
        )
    st.caption("⚠️ AI-generated plan. Review with a qualified advisor before taking action.")


# ─── Chat input ────────────────────────────────────────────────────────────────
user_input = st.chat_input("Describe your idea...")

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})
    st.session_state.session_messages.append({"role": "user", "content": user_input})

    with st.chat_message("user"):
        st.markdown(user_input)

    is_planning = any(trigger in user_input.lower() for trigger in PLAN_TRIGGERS)

    with st.chat_message("assistant"):

        # ── Planning flow ──────────────────────────────────────────────────────
        if is_planning:
            status = st.empty()
            status.markdown("🔨 **ProjectSmith is working on your plan...**")
            st.divider()

            st.markdown("**📋 Plan**")
            plan_box = st.empty()
            plan_box.markdown("_⏳ Analysing your idea..._")

            st.markdown("**💰 Cost & Stack**")
            cost_box = st.empty()
            cost_box.markdown("_⏳ Waiting..._")

            st.markdown("**⚠️ Edge Cases**")
            edges_box = st.empty()
            edges_box.markdown("_⏳ Waiting..._")

            st.markdown("**📄 Project Brief**")
            prd_box = st.empty()
            prd_box.markdown("_⏳ Waiting..._")

            try:
                conversation = build_context(st.session_state.messages)

                result = req.post(
                    f"{API}/plan",
                    json={
                        "user_id":      st.session_state.user_id,
                        "thread_id":    st.session_state.thread_id,
                        "message":      conversation,
                        "conversation": conversation,
                    },
                    timeout=120
                ).json()

                plan_box.markdown(escape_dollars(result.get("plan",  "_No plan returned._")))    # ← fixed
                cost_box.markdown(escape_dollars(result.get("cost",  "_No cost data returned._"))) # ← fixed
                edges_box.markdown(escape_dollars(result.get("edges","_No edge cases returned._"))) # ← fixed
                prd_box.markdown(escape_dollars(result.get("prd",   "_No brief returned._")))    # ← fixed
                status.markdown("✅ **Your project plan is ready!**")

                st.session_state.plan_result = {
                    "plan":  result.get("plan",  ""),
                    "cost":  result.get("cost",  ""),
                    "edges": result.get("edges", ""),
                    "prd":   result.get("prd",   ""),
                }
                st.session_state.messages.append({
                    "role":    "assistant",
                    "content": "✅ Your project plan is ready! Scroll down to see it.",
                })
                st.session_state.session_messages.append({
                    "role":    "assistant",
                    "content": "✅ Your project plan is ready! Scroll down to see it.",
                })

            except req.exceptions.Timeout:
                st.error("❌ The planning request timed out. Try again.")

            except req.exceptions.ConnectionError:
                st.error(f"❌ Could not reach the backend at `{API}`. Is the API server running?")

            except Exception as e:
                st.error(f"❌ Unexpected error: {e}")

            st.rerun()

        # ── Chat flow ──────────────────────────────────────────────────────────
        else:
            response_box = st.empty()
            response     = ""

            try:
                result = req.post(
                    f"{API}/chat",
                    json={
                        "user_id":   st.session_state.user_id,
                        "thread_id": st.session_state.thread_id,
                        "message":   user_input,
                    },
                    timeout=30
                ).json()

                response = escape_dollars(result.get("response", "Sorry, I could not generate a response."))  # ← fixed

            except req.exceptions.Timeout:
                response = "❌ The request timed out. Please try again."

            except req.exceptions.ConnectionError:
                response = f"❌ Could not reach the backend at `{API}`. Is the API server running?"

            except Exception as e:
                response = f"❌ Unexpected error: {e}"

            displayed = ""
            for char in response:
                displayed += char
                response_box.markdown(displayed + "▌")
                time.sleep(0.008)
            response_box.markdown(response)

            st.session_state.messages.append({
                "role":    "assistant",
                "content": response,
            })
            st.session_state.session_messages.append({
                "role":    "assistant",
                "content": response,
            })
